// USERS


// REGISTER USERS
export const USERS_REGISTER_REQUEST = "USERS_REGISTER_REQUEST";
export const USERS_REGISTER_SUCCESS = "USERS_REGISTER_SUCCESS";
export const USERS_REGISTER_FAIL = "USERS_REGISTER_FAIL";

// LOGIN USERS
export const USERS_LOGIN_REQUEST = "USERS_LOGIN_REQUEST";
export const USERS_LOGIN_SUCCESS = "USERS_LOGIN_SUCCESS";
export const USERS_LOGIN_FAIL = "USERS_LOGIN_FAIL";

// LOGOUT USERS
export const USERS_LOGOUT_SUCCESS = "USERS_LOGOUT_SUCCESS";

// PROFILE USERS
export const USERS_PROFILE_REQUEST = "USERS_PROFILE_REQUEST";
export const USERS_PROFILE_SUCCESS = "USERS_PROFILE_SUCCESS";
export const USERS_PROFILE_FAIL = "USERS_PROFILE_FAIL";

// UPDATE USERS
export const USER_UPDATE_REQUEST = "USER_UPDATE_REQUEST";
export const USER_UPDATE_SUCCESS = "USER_UPDATE_SUCCESS";
export const USER_UPDATE_FAIL = "USER_UPDATE_FAIL";

// FETCH USERS
export const FETCH_USERS_REQUEST = "FETCH_USERS_REQUEST";
export const FETCH_USERS_SUCCESS = "FETCH_USERS_SUCCESS";
export const FETCH_USERS_FAIL = "FETCH_USERS_FAIL";



// BOOKS
// CREATE BOOKS
export const CREATE_BOOK_REQUEST = "CREATE_BOOK_REQUEST"
export const CREATE_BOOK_SUCCESS = "CREATE_BOOK_SUCCESS"
export const CREATE_BOOK_FAIL = "CREATE_BOOK_FAIL"

// FETCH BOOKS
export const FETCH_BOOK_REQUEST = "FETCH_BOOK_REQUEST"
export const FETCH_BOOK_SUCCESS = "FETCH_BOOK_SUCCESS"
export const FETCH_BOOK_FAIL = "FETCH_BOOK_FAIL"

// DELETE BOOKS
export const DELETE_BOOK_REQUEST = "DELETE_BOOK_REQUEST"
export const DELETE_BOOK_SUCCESS = "DELETE_BOOK_SUCCESS"
export const DELETE_BOOK_FAIL = "DELETE_BOOK_FAIL"

// DETAILS BOOKS
export const DETAILS_BOOK_REQUEST = "DETAILS_BOOK_REQUEST"
export const DETAILS_BOOK_SUCCESS = "DETAILS_BOOK_SUCCESS"
export const DETAILS_BOOK_FAIL = "DETAILS_BOOK_FAIL"

// UPDATE BOOKS
export const UPDATE_BOOK_REQUEST = "UPDATE_BOOK_REQUEST"
export const UPDATE_BOOK_SUCCESS = "UPDATE_BOOK_SUCCESS"
export const UPDATE_BOOK_FAIL = "UPDATE_BOOK_FAIL"

// SEARCH BOOKS
export const SEARCH_BOOK_REQUEST = "SEARCH_BOOK_REQUEST"
export const SEARCH_BOOK_SUCCESS = "SEARCH_BOOK_SUCCESS"
export const SEARCH_BOOK_FAIL = "SEARCH_BOOK_FAIL"

// FILTER BOOKS
export const FILTER_BOOKS = 'FILTER_BOOKS';